# Nombre del workflow
name: Linter (ESLint)

on:
  pull_request:

jobs:
  client-lint:
    name: Client Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: client/pnpm-lock.yaml

      - name: Install client dependencies
        working-directory: ./client
        run: pnpm install

      - name: Run client lint
        working-directory: ./client
        run: pnpm lint

  server-lint:
    name: Server Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: server/pnpm-lock.yaml

      - name: Install server dependencies
        working-directory: ./server
        run: pnpm install

      - name: Run server lint
        working-directory: ./server
        run: pnpm lint
