# Nombre del workflow
name: Server Tests

# Se ejecuta solo en Pull Requests (a cualquier rama)
on:
  pull_request:

jobs:
  # --- TRABAJO PARA PRUEBAS DEL SERVIDOR ---
  server-test:
    name: Server Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: server/pnpm-lock.yaml

      - name: Install server dependencies
        working-directory: ./server
        run: pnpm install

      # Ejecuta solo los tests
      - name: Run server tests
        working-directory: ./server
        run: pnpm test
